import pycountry

class JustWatchCountries:
    def __init__(self) -> None:
        pass

    def get_all_countries(self):
        countries = []

        for country in pycountry.countries:
            countries.append(country.alpha_2)

        countries.sort()
        return countries

    def get_available_countries(self):
        coutries = [
            "dz",
            "al",
            "ad",
            "ar",
            "au",
            "bs",
            "bh",
            "bb",
            "be",
            "bo",
            "ba",
            "br",
            "bg",
            "cl",
            "cr",
            "ci",
            "de",
            "do",
            "dk",
            "ec",
            "sv",
            "ee",
            "fi",
            "fr",
            "gf",
            "gh",
            "gr",
            "gt",
            "hn",
            "hk",
            "in",
            "id",
            "iq",
            "ie",
            "is",
            "il",
            "it",
            "jm",
            "jp",
            "ye",
            "jo",
            "ca",
            "qa",
            "ke",
            "co",
            "hr",
            "kw",
            "lv",
            "lb",
            "ly",
            "li",
            "lt",
            "my",
            "mt",
            "ma",
            "mu",
            "mx",
            "md",
            "mc",
            "mz",
            "nz",
            "nl",
            "ne",
            "ng",
            "no",
            "om",
            "ps",
            "pa",
            "py",
            "pe",
            "ph",
            "pl",
            "pt",
            "ro",
            "ru",
            "zm",
            "sa",
            "se",
            "ch",
            "sn",
            "sc",
            "sg",
            "sk",
            "es",
            "za",
            "kr",
            "tw",
            "tz",
            "th",
            "tt",
            "cz",
            "tn",
            "tr",
            "ug",
            "hu",
            "uy",
            "ve",
            "ae",
            "us",
            # "uk",
            "eg",
            "gq",
            "at"
        ]
        coutries.sort()
        return coutries